In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 한글 문제
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 17,8

import warnings
warnings.filterwarnings(action='ignore')

# **📌 대구 교통 사고 피해 예측 AI 경진대회 Baseline Code**

## **Fixed Random Seed**  

seed 값에 의해 동일한 코드를 사용해도 결과가 다를 수 있기에, 동일한 결과를 위해 seed 값을 고정시킵니다

In [2]:
import os
import random
import numpy as np

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42)

## **데이터 불러오기 및 상위행 확인**  

train.csv, test.csv 파일을 로드하여 상위행을 출력해 봅시다

In [3]:
import pandas as pd
from datetime import datetime

train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')

display(train.head())
display(test.tail())

ID           사고일시   요일 기상상태            시군구      도로형태 노면상태  \
0  ACCIDENT_00000  2019-01-01 00  화요일   맑음   대구광역시 중구 대신동  단일로 - 기타   건조   
1  ACCIDENT_00001  2019-01-01 00  화요일   흐림  대구광역시 달서구 감삼동  단일로 - 기타   건조   
2  ACCIDENT_00002  2019-01-01 01  화요일   맑음  대구광역시 수성구 두산동  단일로 - 기타   건조   
3  ACCIDENT_00003  2019-01-01 02  화요일   맑음   대구광역시 북구 복현동  단일로 - 기타   건조   
4  ACCIDENT_00004  2019-01-01 04  화요일   맑음   대구광역시 동구 신암동  단일로 - 기타   건조   

   사고유형 사고유형 - 세부분류     법규위반  ... 가해운전자 상해정도 피해운전자 차종 피해운전자 성별 피해운전자 연령  \
0  차대사람  길가장자리구역통행중  안전운전불이행  ...       상해없음      보행자        여      70세   
1  차대사람       보도통행중       기타  ...       상해없음      보행자        남      61세   
2  차대사람       차도통행중  안전운전불이행  ...       상해없음      보행자        남      38세   
3   차대차          추돌  안전운전불이행  ...       상해없음       승용        남      36세   
4   차대차          추돌  안전운전불이행  ...       상해없음       승용        남      52세   

  피해운전자 상해정도 사망자수 중상자수 경상자수  부상자수  ECLO  
0         중상    0    1    0     0     5  
1         경상    0    0    1     0     3  
2         경상    0    0    1     0     3  
3         중상    0    1    0     0     5  
4         경상    0    0    1     0     3  

[5 rows x 23 columns]

ID           사고일시   요일 기상상태            시군구         도로형태  \
10958  ACCIDENT_50567  2022-12-31 18  토요일   맑음   대구광역시 남구 대명동     단일로 - 터널   
10959  ACCIDENT_50568  2022-12-31 18  토요일   맑음  대구광역시 수성구 시지동     단일로 - 기타   
10960  ACCIDENT_50569  2022-12-31 20  토요일   맑음  대구광역시 수성구 연호동     단일로 - 기타   
10961  ACCIDENT_50570  2022-12-31 20  토요일   맑음  대구광역시 수성구 범물동  교차로 - 교차로부근   
10962  ACCIDENT_50571  2022-12-31 21  토요일   맑음   대구광역시 동구 효목동  교차로 - 교차로부근   

      노면상태 사고유형  
10958   건조  차대차  
10959   건조  차대차  
10960   건조  차대차  
10961   건조  차대차  
10962   건조  차대차

## **train, test 데이터 기간 확인하기**  

학습(train) 데이터의 기간과 예측 대상이 되는 test 데이터의 기간을 살펴 봅니다

In [4]:
display(f"train : {train.iloc[0]['사고일시']} ~ {train.iloc[-1]['사고일시']}")
display(f"test : {test.iloc[0]['사고일시']} ~ {test.iloc[-1]['사고일시']}")

'train : 2019-01-01 00 ~ 2021-12-31 23'

'test : 2022-01-01 01 ~ 2022-12-31 21'

### Data Info

In [5]:
#'사고일시' 데이터 타입을 object -> datetime으로  바꾸기
train['사고일시'] = pd.to_datetime(train['사고일시'])
test['사고일시'] = pd.to_datetime(test['사고일시'])

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39609 entries, 0 to 39608
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   ID           39609 non-null  object        
 1   사고일시         39609 non-null  datetime64[ns]
 2   요일           39609 non-null  object        
 3   기상상태         39609 non-null  object        
 4   시군구          39609 non-null  object        
 5   도로형태         39609 non-null  object        
 6   노면상태         39609 non-null  object        
 7   사고유형         39609 non-null  object        
 8   사고유형 - 세부분류  39609 non-null  object        
 9   법규위반         39609 non-null  object        
 10  가해운전자 차종     39609 non-null  object        
 11  가해운전자 성별     39609 non-null  object        
 12  가해운전자 연령     39609 non-null  object        
 13  가해운전자 상해정도   39609 non-null  object        
 14  피해운전자 차종     38618 non-null  object        
 15  피해운전자 성별     38618 non-null  object        
 16  피해운전

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10963 entries, 0 to 10962
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   ID      10963 non-null  object        
 1   사고일시    10963 non-null  datetime64[ns]
 2   요일      10963 non-null  object        
 3   기상상태    10963 non-null  object        
 4   시군구     10963 non-null  object        
 5   도로형태    10963 non-null  object        
 6   노면상태    10963 non-null  object        
 7   사고유형    10963 non-null  object        
dtypes: datetime64[ns](1), object(7)
memory usage: 685.3+ KB


### - train과 test 데이터셋의  컬럼 수가 서로 다름
    - ID, 사고일시, 요일, 기상상태, 시군구, 도로형태, 노면상태, 사고유형

In [8]:
display(train['요일'].unique())
display(test['요일'].unique())

array(['화요일', '수요일', '목요일', '금요일', '토요일', '일요일', '월요일'], dtype=object)

array(['토요일', '일요일', '월요일', '화요일', '수요일', '목요일', '금요일'], dtype=object)

In [9]:
display(train['기상상태'].unique())
display(test['기상상태'].unique())

array(['맑음', '흐림', '기타', '비', '안개', '눈'], dtype=object)

array(['맑음', '흐림', '기타', '비', '눈'], dtype=object)

***- test에는 기상상태-'안개' 없음***

In [10]:
display(train['시군구'].unique())
display(test['시군구'].unique())

array(['대구광역시 중구 대신동', '대구광역시 달서구 감삼동', '대구광역시 수성구 두산동', '대구광역시 북구 복현동',
       '대구광역시 동구 신암동', '대구광역시 수성구 지산동', '대구광역시 달서구 상인동', '대구광역시 북구 태전동',
       '대구광역시 동구 지묘동', '대구광역시 서구 평리동', '대구광역시 동구 신기동', '대구광역시 서구 상리동',
       '대구광역시 달서구 월성동', '대구광역시 수성구 황금동', '대구광역시 북구 구암동', '대구광역시 동구 신천동',
       '대구광역시 수성구 만촌동', '대구광역시 중구 남산동', '대구광역시 서구 비산동', '대구광역시 북구 침산동',
       '대구광역시 달서구 두류동', '대구광역시 수성구 신매동', '대구광역시 달서구 대곡동', '대구광역시 달성군 유가읍',
       '대구광역시 달성군 논공읍', '대구광역시 동구 율하동', '대구광역시 수성구 시지동', '대구광역시 동구 봉무동',
       '대구광역시 달성군 다사읍', '대구광역시 중구 동산동', '대구광역시 서구 이현동', '대구광역시 남구 이천동',
       '대구광역시 수성구 수성동4가', '대구광역시 북구 노원동3가', '대구광역시 북구 서변동',
       '대구광역시 북구 관음동', '대구광역시 북구 학정동', '대구광역시 수성구 파동', '대구광역시 수성구 상동',
       '대구광역시 달서구 이곡동', '대구광역시 동구 효목동', '대구광역시 북구 읍내동', '대구광역시 중구 남성로',
       '대구광역시 달서구 죽전동', '대구광역시 남구 대명동', '대구광역시 북구 동천동', '대구광역시 동구 지저동',
       '대구광역시 북구 사수동', '대구광역시 중구 덕산동', '대구광역시 달서구 본리동', '대구광역시 동구 용계동',
       '대구광역시 수성구 범어동', '대구광역시 달서구 신당동', '대구광역시 달서구 성당동', '대구광역시 달서구 용산

array(['대구광역시 수성구 상동', '대구광역시 수성구 지산동', '대구광역시 수성구 수성동2가',
       '대구광역시 수성구 신매동', '대구광역시 달서구 감삼동', '대구광역시 중구 달성동', '대구광역시 동구 신암동',
       '대구광역시 서구 평리동', '대구광역시 달서구 송현동', '대구광역시 달서구 두류동', '대구광역시 북구 매천동',
       '대구광역시 달서구 상인동', '대구광역시 달서구 진천동', '대구광역시 중구 삼덕동1가', '대구광역시 중구 동문동',
       '대구광역시 달서구 성당동', '대구광역시 북구 동천동', '대구광역시 북구 태전동', '대구광역시 남구 대명동',
       '대구광역시 달서구 대곡동', '대구광역시 북구 복현동', '대구광역시 달서구 본리동', '대구광역시 수성구 범어동',
       '대구광역시 수성구 황금동', '대구광역시 달서구 호산동', '대구광역시 중구 동인동1가', '대구광역시 남구 이천동',
       '대구광역시 달성군 유가읍', '대구광역시 달서구 월암동', '대구광역시 북구 동호동', '대구광역시 달서구 죽전동',
       '대구광역시 달서구 본동', '대구광역시 달서구 도원동', '대구광역시 달성군 다사읍', '대구광역시 달서구 용산동',
       '대구광역시 달서구 유천동', '대구광역시 북구 산격동', '대구광역시 달서구 파호동', '대구광역시 동구 효목동',
       '대구광역시 북구 고성동3가', '대구광역시 중구 남산동', '대구광역시 동구 지묘동', '대구광역시 달성군 하빈면',
       '대구광역시 서구 내당동', '대구광역시 수성구 매호동', '대구광역시 북구 침산동', '대구광역시 동구 신천동',
       '대구광역시 동구 방촌동', '대구광역시 수성구 두산동', '대구광역시 달성군 구지면', '대구광역시 달서구 대천동',
       '대구광역시 달서구 월성동', '대구광역시 달성군 화원읍', '대구광역시 북구 고성동2가',

In [11]:
display(train['도로형태'].unique())
display(test['도로형태'].unique())

array(['단일로 - 기타', '교차로 - 교차로안', '기타 - 기타', '단일로 - 터널', '단일로 - 지하차도(도로)내',
       '단일로 - 교량', '교차로 - 교차로횡단보도내', '주차장 - 주차장', '교차로 - 교차로부근',
       '단일로 - 고가도로위', '미분류 - 미분류'], dtype=object)

array(['교차로 - 교차로안', '단일로 - 기타', '교차로 - 교차로횡단보도내', '교차로 - 교차로부근',
       '단일로 - 지하차도(도로)내', '기타 - 기타', '단일로 - 교량', '단일로 - 고가도로위',
       '주차장 - 주차장', '단일로 - 터널', '미분류 - 미분류'], dtype=object)

In [12]:
display(train['노면상태'].unique())
display(test['노면상태'].unique())

array(['건조', '젖음/습기', '서리/결빙', '기타', '침수', '적설'], dtype=object)

array(['건조', '젖음/습기', '서리/결빙', '기타', '침수', '적설'], dtype=object)

In [13]:
display(train['사고유형'].unique())
display(test['사고유형'].unique())

array(['차대사람', '차대차', '차량단독'], dtype=object)

array(['차대사람', '차대차', '차량단독'], dtype=object)

### 날짜 데이터 파싱하기

In [14]:
train['year'] = train.사고일시.dt.year
train['month'] = train.사고일시.dt.month
train['day'] = train.사고일시.dt.day
train['hour'] = train.사고일시.dt.hour

In [15]:
test['year'] = test.사고일시.dt.year
test['month'] = test.사고일시.dt.month
test['day'] = test.사고일시.dt.day
test['hour'] = test.사고일시.dt.hour

## **데이터 전처리**  

현재 '사고일시', '시군구', '도로형태' 컬럼은 반복되는 패턴으로 여러 정보를 포함하고 있습니다
이런 반복되는 패턴을 일반화하면 pandas에서 제공하는 str.extract를 통해 한 번에 추출 가능합니다  

## **파생 변수 생성 1 : 날짜, 시간정보 생성**

'사고일시' 컬럼으로 부터 연도, 월, 일, 시간 정보 추출 및 변환 합니다

In [16]:
import pandas as pd
from datetime import datetime

train_org = pd.read_csv('./data/train.csv')
test_org = pd.read_csv('./data/test.csv')

display(train_org.head())
display(test_org.tail())

ID           사고일시   요일 기상상태            시군구      도로형태 노면상태  \
0  ACCIDENT_00000  2019-01-01 00  화요일   맑음   대구광역시 중구 대신동  단일로 - 기타   건조   
1  ACCIDENT_00001  2019-01-01 00  화요일   흐림  대구광역시 달서구 감삼동  단일로 - 기타   건조   
2  ACCIDENT_00002  2019-01-01 01  화요일   맑음  대구광역시 수성구 두산동  단일로 - 기타   건조   
3  ACCIDENT_00003  2019-01-01 02  화요일   맑음   대구광역시 북구 복현동  단일로 - 기타   건조   
4  ACCIDENT_00004  2019-01-01 04  화요일   맑음   대구광역시 동구 신암동  단일로 - 기타   건조   

   사고유형 사고유형 - 세부분류     법규위반  ... 가해운전자 상해정도 피해운전자 차종 피해운전자 성별 피해운전자 연령  \
0  차대사람  길가장자리구역통행중  안전운전불이행  ...       상해없음      보행자        여      70세   
1  차대사람       보도통행중       기타  ...       상해없음      보행자        남      61세   
2  차대사람       차도통행중  안전운전불이행  ...       상해없음      보행자        남      38세   
3   차대차          추돌  안전운전불이행  ...       상해없음       승용        남      36세   
4   차대차          추돌  안전운전불이행  ...       상해없음       승용        남      52세   

  피해운전자 상해정도 사망자수 중상자수 경상자수  부상자수  ECLO  
0         중상    0    1    0     0     5  
1         경상    0    0    1     0     3  
2         경상    0    0    1     0     3  
3         중상    0    1    0     0     5  
4         경상    0    0    1     0     3  

[5 rows x 23 columns]

ID           사고일시   요일 기상상태            시군구         도로형태  \
10958  ACCIDENT_50567  2022-12-31 18  토요일   맑음   대구광역시 남구 대명동     단일로 - 터널   
10959  ACCIDENT_50568  2022-12-31 18  토요일   맑음  대구광역시 수성구 시지동     단일로 - 기타   
10960  ACCIDENT_50569  2022-12-31 20  토요일   맑음  대구광역시 수성구 연호동     단일로 - 기타   
10961  ACCIDENT_50570  2022-12-31 20  토요일   맑음  대구광역시 수성구 범물동  교차로 - 교차로부근   
10962  ACCIDENT_50571  2022-12-31 21  토요일   맑음   대구광역시 동구 효목동  교차로 - 교차로부근   

      노면상태 사고유형  
10958   건조  차대차  
10959   건조  차대차  
10960   건조  차대차  
10961   건조  차대차  
10962   건조  차대차

In [17]:
train_df = train_org.copy()
test_df = test_org.copy()

time_pattern = r'(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2})'

train_df[['연', '월', '일', '시간']] = train_org['사고일시'].str.extract(time_pattern)
train_df[['연', '월', '일', '시간']] = train_df[['연', '월', '일', '시간']].apply(pd.to_numeric) # 추출된 문자열을 수치화해줍니다
train_df = train_df.drop(columns=['사고일시']) # 정보 추출이 완료된 '사고일시' 컬럼은 제거합니다

# 해당 과정을 test_x에 대해서도 반복해줍니다
test_df[['연', '월', '일', '시간']] = test_org['사고일시'].str.extract(time_pattern)
test_df[['연', '월', '일', '시간']] = test_df[['연', '월', '일', '시간']].apply(pd.to_numeric)
test_df = test_df.drop(columns=['사고일시'])

display(f"columns of train_df : {train_df.columns}")
display(f"columns of test_df : {test_df.columns}")

"columns of train_df : Index(['ID', '요일', '기상상태', '시군구', '도로형태', '노면상태', '사고유형', '사고유형 - 세부분류',\n       '법규위반', '가해운전자 차종', '가해운전자 성별', '가해운전자 연령', '가해운전자 상해정도', '피해운전자 차종',\n       '피해운전자 성별', '피해운전자 연령', '피해운전자 상해정도', '사망자수', '중상자수', '경상자수', '부상자수',\n       'ECLO', '연', '월', '일', '시간'],\n      dtype='object')"

"columns of test_df : Index(['ID', '요일', '기상상태', '시군구', '도로형태', '노면상태', '사고유형', '연', '월', '일', '시간'], dtype='object')"

## **파생 변수 생성 2 : 공간(위치) 정보 생성**

'시군구' 컬럼으로부터 의미 있는 공산 정보를 추출 및 변환 합니다

In [18]:
location_pattern = r'(\S+) (\S+) (\S+)'

train_df[['도시', '구', '동']] = train_org['시군구'].str.extract(location_pattern)
train_df = train_df.drop(columns=['시군구'])

test_df[['도시', '구', '동']] = test_org['시군구'].str.extract(location_pattern)
test_df = test_df.drop(columns=['시군구'])

display(f"columns of train_df : {train_df.columns}")
display(f"columns of test_df : {test_df.columns}")

"columns of train_df : Index(['ID', '요일', '기상상태', '도로형태', '노면상태', '사고유형', '사고유형 - 세부분류', '법규위반',\n       '가해운전자 차종', '가해운전자 성별', '가해운전자 연령', '가해운전자 상해정도', '피해운전자 차종',\n       '피해운전자 성별', '피해운전자 연령', '피해운전자 상해정도', '사망자수', '중상자수', '경상자수', '부상자수',\n       'ECLO', '연', '월', '일', '시간', '도시', '구', '동'],\n      dtype='object')"

"columns of test_df : Index(['ID', '요일', '기상상태', '도로형태', '노면상태', '사고유형', '연', '월', '일', '시간', '도시',\n       '구', '동'],\n      dtype='object')"

## **파생 변수 추출 3 : 도로 형태 정보 추출**  

'도로형태' 컬럼은 '단일로 - 기타'와 같은 패턴으로 구성되어 있습니다. 이를 두종류의 독립된 정보로 보고 두개의 컬럼으로 분리하여 생성합니다.

In [19]:
road_pattern = r'(.+) - (.+)'

train_df[['도로형태1', '도로형태2']] = train_org['도로형태'].str.extract(road_pattern)
train_df = train_df.drop(columns=['도로형태'])

test_df[['도로형태1', '도로형태2']] = test_org['도로형태'].str.extract(road_pattern)
test_df = test_df.drop(columns=['도로형태'])

display(f"columns of train_df : {train_df.columns}")
display(f"columns of test_df : {test_df.columns}")

"columns of train_df : Index(['ID', '요일', '기상상태', '노면상태', '사고유형', '사고유형 - 세부분류', '법규위반', '가해운전자 차종',\n       '가해운전자 성별', '가해운전자 연령', '가해운전자 상해정도', '피해운전자 차종', '피해운전자 성별',\n       '피해운전자 연령', '피해운전자 상해정도', '사망자수', '중상자수', '경상자수', '부상자수', 'ECLO', '연',\n       '월', '일', '시간', '도시', '구', '동', '도로형태1', '도로형태2'],\n      dtype='object')"

"columns of test_df : Index(['ID', '요일', '기상상태', '노면상태', '사고유형', '연', '월', '일', '시간', '도시', '구', '동',\n       '도로형태1', '도로형태2'],\n      dtype='object')"

## train, test 컬럼 수 맞추기

test에 있는 컬럼들만 사용하여 train 데이터를 구성했습니다.

In [20]:
train_df= train_df[['ID','요일','기상상태','노면상태', '사고유형', '연', '월', '일', '시간', '도시', '구','동', '도로형태1', '도로형태2']]
train_df

ID   요일 기상상태 노면상태  사고유형     연   월   일  시간     도시    구  \
0      ACCIDENT_00000  화요일   맑음   건조  차대사람  2019   1   1   0  대구광역시   중구   
1      ACCIDENT_00001  화요일   흐림   건조  차대사람  2019   1   1   0  대구광역시  달서구   
2      ACCIDENT_00002  화요일   맑음   건조  차대사람  2019   1   1   1  대구광역시  수성구   
3      ACCIDENT_00003  화요일   맑음   건조   차대차  2019   1   1   2  대구광역시   북구   
4      ACCIDENT_00004  화요일   맑음   건조   차대차  2019   1   1   4  대구광역시   동구   
...               ...  ...  ...  ...   ...   ...  ..  ..  ..    ...  ...   
39604  ACCIDENT_39604  금요일   맑음   건조   차대차  2021  12  31  19  대구광역시  수성구   
39605  ACCIDENT_39605  금요일   맑음   건조   차대차  2021  12  31  19  대구광역시  달서구   
39606  ACCIDENT_39606  금요일   맑음   건조   차대차  2021  12  31  21  대구광역시  달서구   
39607  ACCIDENT_39607  금요일   맑음   건조   차대차  2021  12  31  22  대구광역시  달서구   
39608  ACCIDENT_39608  금요일   맑음   건조   차대차  2021  12  31  23  대구광역시   서구   

           동 도로형태1      도로형태2  
0        대신동   단일로         기타  
1        감삼동   단일로         기타  
2        두산동   단일로         기타  
3        복현동   단일로         기타  
4        신암동   단일로         기타  
...      ...   ...        ...  
39604  수성동3가   교차로       교차로안  
39605    상인동   단일로         기타  
39606    월성동   교차로       교차로안  
39607     장동    기타         기타  
39608    비산동   단일로  지하차도(도로)내  

[39609 rows x 14 columns]

## **전처리 결과 확인**

지금까지 전처리한 결과를 확인해 봅시다

In [21]:
display(train_df.head())
display(test_df.head())

ID   요일 기상상태 노면상태  사고유형     연  월  일  시간     도시    구    동 도로형태1  \
0  ACCIDENT_00000  화요일   맑음   건조  차대사람  2019  1  1   0  대구광역시   중구  대신동   단일로   
1  ACCIDENT_00001  화요일   흐림   건조  차대사람  2019  1  1   0  대구광역시  달서구  감삼동   단일로   
2  ACCIDENT_00002  화요일   맑음   건조  차대사람  2019  1  1   1  대구광역시  수성구  두산동   단일로   
3  ACCIDENT_00003  화요일   맑음   건조   차대차  2019  1  1   2  대구광역시   북구  복현동   단일로   
4  ACCIDENT_00004  화요일   맑음   건조   차대차  2019  1  1   4  대구광역시   동구  신암동   단일로   

  도로형태2  
0    기타  
1    기타  
2    기타  
3    기타  
4    기타

ID   요일 기상상태 노면상태  사고유형     연  월  일  시간     도시    구      동  \
0  ACCIDENT_39609  토요일   맑음   건조  차대사람  2022  1  1   1  대구광역시  수성구     상동   
1  ACCIDENT_39610  토요일   맑음   건조  차대사람  2022  1  1   1  대구광역시  수성구    지산동   
2  ACCIDENT_39611  토요일   맑음   건조   차대차  2022  1  1   4  대구광역시  수성구  수성동2가   
3  ACCIDENT_39612  토요일   맑음   건조   차대차  2022  1  1   4  대구광역시  수성구    신매동   
4  ACCIDENT_39613  토요일   맑음   건조   차대차  2022  1  1   6  대구광역시  달서구    감삼동   

  도로형태1 도로형태2  
0   교차로  교차로안  
1   단일로    기타  
2   교차로  교차로안  
3   단일로    기타  
4   교차로  교차로안

## **train과 test 데이터 합치기**

In [25]:
data = pd.concat([train_df, test_df], sort=False)
data.head()

ID   요일 기상상태 노면상태  사고유형     연  월  일  시간     도시    구    동 도로형태1  \
0  ACCIDENT_00000  화요일   맑음   건조  차대사람  2019  1  1   0  대구광역시   중구  대신동   단일로   
1  ACCIDENT_00001  화요일   흐림   건조  차대사람  2019  1  1   0  대구광역시  달서구  감삼동   단일로   
2  ACCIDENT_00002  화요일   맑음   건조  차대사람  2019  1  1   1  대구광역시  수성구  두산동   단일로   
3  ACCIDENT_00003  화요일   맑음   건조   차대차  2019  1  1   2  대구광역시   북구  복현동   단일로   
4  ACCIDENT_00004  화요일   맑음   건조   차대차  2019  1  1   4  대구광역시   동구  신암동   단일로   

  도로형태2  
0    기타  
1    기타  
2    기타  
3    기타  
4    기타

# **⭐️ 구,동 인코딩 적용**

## **원-핫 인코딩 적용**

In [49]:
from sklearn.preprocessing import OneHotEncoder

### 구 
- `ohe_gu` : 원-핫 인코딩 적용된 배열
- `ohe_gu_df` : `ohe_gu` 의 df

**1. 구 정보 확인**

In [56]:
label_gu = data['구']
print(label_gu.unique())
print(label_gu.shape)

['중구' '달서구' '수성구' '북구' '동구' '서구' '달성군' '남구']
(50572,)


**2. 원-핫 인코딩 적용**

In [57]:
# 1. OneHotEncoder 임포트 및 정의 
ohe = OneHotEncoder(sparse=False) # array 반환을 위해 sparse=False

# 2. 2차원 데이터로 반환 
label_gu_rs = label_gu.values.reshape(-1, 1)

# 3. One-Hot Encoding 적용
ohe.fit(label_gu_rs)

# 4. One-Hot Encoding 적용된 배열 리턴 
ohe_gu = ohe.transform(label_gu_rs)

In [58]:
print('One-Hot Encoding 적용된 배열: ', ohe_gu)
print('One-Hot Encoding 카테고리 확인: ', ohe.categories_)

One-Hot Encoding 적용된 배열:  [[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
One-Hot Encoding 카테고리 확인:  [array(['남구', '달서구', '달성군', '동구', '북구', '서구', '수성구', '중구'], dtype=object)]


In [59]:
ohe_gu_df = pd.DataFrame(ohe_gu, columns=ohe.categories_[0])
ohe_gu_df

남구  달서구  달성군   동구   북구   서구  수성구   중구
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
1      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...
50567  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
50568  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
50569  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
50570  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
50571  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[50572 rows x 8 columns]

### 동
- `ohe_dong` : 원-핫 인코딩 적용된 배열
- `ohe_dong_df` : ohe_dong 의 df

**1. 동 정보 확인**

In [87]:
label_dong = data['동']
print(label_dong.unique())
print(label_dong.shape)

['대신동' '감삼동' '두산동' '복현동' '신암동' '지산동' '상인동' '태전동' '지묘동' '평리동' '신기동' '상리동'
 '월성동' '황금동' '구암동' '신천동' '만촌동' '남산동' '비산동' '침산동' '두류동' '신매동' '대곡동' '유가읍'
 '논공읍' '율하동' '시지동' '봉무동' '다사읍' '동산동' '이현동' '이천동' '수성동4가' '노원동3가' '서변동'
 '관음동' '학정동' '파동' '상동' '이곡동' '효목동' '읍내동' '남성로' '죽전동' '대명동' '동천동' '지저동'
 '사수동' '덕산동' '본리동' '용계동' '범어동' '신당동' '성당동' '용산동' '태평로3가' '도학동' '욱수동' '불로동'
 '칠성동1가' '장기동' '매호동' '대천동' '삼덕동1가' '수성동2가' '팔달동' '삼덕동' '진천동' '수성동3가' '가창면'
 '방촌동' '산격동' '월암동' '현풍읍' '구지면' '매천동' '송현동' '고성동3가' '봉덕동' '칠성동2가' '공평동'
 '봉산동' '괴전동' '국우동' '대현동' '노원동1가' '대봉동' '본동' '신서동' '검단동' '화원읍' '동호동'
 '삼덕동2가' '입석동' '중동' '삼덕동3가' '파호동' '동내동' '하빈면' '율암동' '동인동1가' '내당동' '유천동'
 '호산동' '교동' '옥포읍' '원대동3가' '검사동' '동인동4가' '수성동1가' '고성동2가' '각산동' '중리동'
 '고성동1가' '갈산동' '대림동' '호림동' '연호동' '동변동' '범물동' '계산동2가' '동문동' '고모동' '금호동'
 '장동' '도원동' '수창동' '동인동2가' '가천동' '노변동' '달성동' '동인동3가' '서문로2가' '동성로2가' '중대동'
 '사월동' '장관동' '신평동' '숙천동' '성동' '동일동' '시장북로' '서호동' '용수동' '대흥동' '동성로3가' '연경동'
 '원대동1가' '남일동' '부동' '송정동' '백안동' '도동' '인교동' '미대동' '노원동2가' '북성로1가

**2. 원-핫 인코딩 적용**

In [61]:
# 1. OneHotEncoder 임포트 및 정의 
ohe = OneHotEncoder(sparse=False) # array 반환을 위해 sparse=False

# 2. 2차원 데이터로 반환 
label_dong_rs = label_dong.values.reshape(-1, 1)

# 3. One-Hot Encoding 적용
ohe.fit(label_dong_rs)

# 4. One-Hot Encoding 적용된 배열 리턴 
ohe_dong = ohe.transform(label_dong_rs)

In [62]:
print('One-Hot Encoding 적용된 배열: ', ohe_dong)
print('One-Hot Encoding 카테고리 확인: ', ohe.categories_)

One-Hot Encoding 적용된 배열:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
One-Hot Encoding 카테고리 확인:  [array(['가창면', '가천동', '각산동', '갈산동', '감삼동', '검단동', '검사동', '계산동1가', '계산동2가',
       '고모동', '고성동1가', '고성동2가', '고성동3가', '공평동', '관음동', '괴전동', '교동', '구암동',
       '구지면', '국우동', '금강동', '금호동', '남산동', '남성로', '남일동', '내당동', '내동',
       '노곡동', '노변동', '노원동1가', '노원동2가', '노원동3가', '논공읍', '능성동', '다사읍',
       '달성동', '대곡동', '대림동', '대명동', '대봉동', '대신동', '대안동', '대천동', '대현동',
       '대흥동', '덕곡동', '덕산동', '도남동', '도동', '도원동', '도학동', '동내동', '동문동',
       '동변동', '동산동', '동성로1가', '동성로2가', '동성로3가', '동인동1가', '동인동2가', '동인동3가',
       '동인동4가', '동일동', '동천동', '동호동', '두류동', '두산동', '둔산동', '만촌동', '매여동',
       '매천동', '매호동', '문화동', '미곡동', '미대동', '방촌동', '백안동', '범물동', '범어동',
       '복현동', '본동', '본리동', '봉덕동', '봉무동', '봉산동', '부동', '북성로1가', '북성로2가',
       '불로동', '비산동', '사복동', '사수동', '사월동', '사일동', '산격동', '삼덕동', '삼덕동1가',
   

In [63]:
ohe_dong_df = pd.DataFrame(ohe_dong, columns=ohe.categories_[0])
ohe_dong_df

가창면  가천동  각산동  갈산동  감삼동  검단동  검사동  계산동1가  계산동2가  고모동  ...  하서동  학정동  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
1      0.0  0.0  0.0  0.0  1.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...    ...    ...  ...  ...  ...  ...   
50567  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
50568  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
50569  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
50570  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   
50571  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0  0.0  ...  0.0  0.0   

       향촌동  현풍읍  호림동  호산동  화원읍  화전동  황금동  효목동  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  ...  
50567  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
50568  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
50569  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
50570  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
50571  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

[50572 rows x 196 columns]

## **레이블 인코딩 적용**

### 구 
- `le_gu` : 레이블 인코딩 적용된 배열
- `le_gu_df` : `le_gu` 의 df

In [67]:
from sklearn.preprocessing import LabelEncoder

**1. 구 정보 확인**

In [68]:
label_gu = data['구']
print(label_gu.unique())
print(label_gu.shape)

['중구' '달서구' '수성구' '북구' '동구' '서구' '달성군' '남구']
(50572,)


**2. 레이블 인코딩 적용**

In [80]:
# 1. LabelEncoder 임포트 및 정의 
le = LabelEncoder()

# 2. 2차원 데이터로 반환 
label_gu_rs = label_gu.values.reshape(-1, 1)

# 2. LabelEncoder 적용
le_gu = le.fit_transform(label_gu_rs)

In [81]:
print(set(le_gu))
print(le.classes_)
print(le.inverse_transform([0, 1, 2, 3, 4, 5, 6, 7]))

{0, 1, 2, 3, 4, 5, 6, 7}
['남구' '달서구' '달성군' '동구' '북구' '서구' '수성구' '중구']
['남구' '달서구' '달성군' '동구' '북구' '서구' '수성구' '중구']


In [86]:
le_gu_df = pd.DataFrame(le_gu, columns=['구'])
le_gu_df

구
0      7
1      1
2      6
3      4
4      3
...   ..
50567  0
50568  6
50569  6
50570  6
50571  3

[50572 rows x 1 columns]

### 동
- `le_dong` : 레이블 인코딩 적용된 배열
- `le_dong_df` : le_dong 의 df

**1. 동 정보 확인**

In [88]:
label_dong = data['동']
print(label_dong.unique())
print(label_dong.shape)

['대신동' '감삼동' '두산동' '복현동' '신암동' '지산동' '상인동' '태전동' '지묘동' '평리동' '신기동' '상리동'
 '월성동' '황금동' '구암동' '신천동' '만촌동' '남산동' '비산동' '침산동' '두류동' '신매동' '대곡동' '유가읍'
 '논공읍' '율하동' '시지동' '봉무동' '다사읍' '동산동' '이현동' '이천동' '수성동4가' '노원동3가' '서변동'
 '관음동' '학정동' '파동' '상동' '이곡동' '효목동' '읍내동' '남성로' '죽전동' '대명동' '동천동' '지저동'
 '사수동' '덕산동' '본리동' '용계동' '범어동' '신당동' '성당동' '용산동' '태평로3가' '도학동' '욱수동' '불로동'
 '칠성동1가' '장기동' '매호동' '대천동' '삼덕동1가' '수성동2가' '팔달동' '삼덕동' '진천동' '수성동3가' '가창면'
 '방촌동' '산격동' '월암동' '현풍읍' '구지면' '매천동' '송현동' '고성동3가' '봉덕동' '칠성동2가' '공평동'
 '봉산동' '괴전동' '국우동' '대현동' '노원동1가' '대봉동' '본동' '신서동' '검단동' '화원읍' '동호동'
 '삼덕동2가' '입석동' '중동' '삼덕동3가' '파호동' '동내동' '하빈면' '율암동' '동인동1가' '내당동' '유천동'
 '호산동' '교동' '옥포읍' '원대동3가' '검사동' '동인동4가' '수성동1가' '고성동2가' '각산동' '중리동'
 '고성동1가' '갈산동' '대림동' '호림동' '연호동' '동변동' '범물동' '계산동2가' '동문동' '고모동' '금호동'
 '장동' '도원동' '수창동' '동인동2가' '가천동' '노변동' '달성동' '동인동3가' '서문로2가' '동성로2가' '중대동'
 '사월동' '장관동' '신평동' '숙천동' '성동' '동일동' '시장북로' '서호동' '용수동' '대흥동' '동성로3가' '연경동'
 '원대동1가' '남일동' '부동' '송정동' '백안동' '도동' '인교동' '미대동' '노원동2가' '북성로1가

**2. 레이블 인코딩 적용**

In [90]:
# 1. LabelEncoder 임포트 및 정의 
le = LabelEncoder()

# 2. 2차원 데이터로 반환 
label_dong_rs = label_dong.values.reshape(-1, 1)

# 2. LabelEncoder 적용
le_dong = le.fit_transform(label_dong_rs)

In [91]:
print(set(le_dong))
print(le.classes_)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195}
['가창면' '가천동' '각산동' '갈산동' '감삼동' '검단동' '검사동' '계산동1가' '계산동2가' '고모동' '고성동1가'
 '고성동2가' '고성동3가' '공평동' '관음동' '괴전동' '교동' '구암동' '구지면' '국우동

In [92]:
le_dong_df = pd.DataFrame(le_dong, columns=['동'])
le_dong_df

동
0       40
1        4
2       66
3       79
4      129
...    ...
50567   38
50568  123
50569  134
50570   77
50571  195

[50572 rows x 1 columns]